FROM node:20-alpine AS build

WORKDIR /app/cortex

COPY cortex/package.json /app/cortex/package.json
COPY cortex/package-lock.json /app/cortex/package-lock.json
RUN npm ci

COPY cortex /app/cortex
RUN npm run build

FROM node:20-alpine

WORKDIR /app/cortex

ENV NODE_ENV=production

COPY --from=build /app/cortex /app/cortex

EXPOSE 3000

CMD ["npm", "run", "start"]
